import { clsx, type ClassValue } from "clsx"
import { twMerge } from "tailwind-merge"

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs))
}
export async function getCurrencyForCountry(countryName: string): Promise<string> {
  // A mapping of country names to their currency codes
  // You may want to expand this with more countries as needed
  const countryToCurrency: Record<string, string> = {
    'united states': 'USD',
    'united states of america': 'USD',
    'usa': 'USD',
    'canada': 'CAD',
    'united kingdom': 'GBP',
    'great britain': 'GBP',
    'germany': 'EUR',
    'france': 'EUR',
    'spain': 'EUR',
    'italy': 'EUR',
    'australia': 'AUD',
    'north korea': 'KPW',
    'south korea': 'KRW',
    'japan': 'JPY',
    'china': 'CNY',
    'india': 'INR',
    'indonesia': 'IDR',
    'pakistan': 'PKR',
    'bangladesh': 'BDT',
    'philippines': 'PHP',
    'vietnam': 'VND',
    'thailand': 'THB',
    'malaysia': 'MYR',
    'singapore': 'SGD',
    'hong kong': 'HKD',
    'taiwan': 'TWD',
    'sri lanka': 'LKR',
    'nepal': 'NPR',
    'cambodia': 'KHR',
    'myanmar': 'MMK',
    'laos': 'LAK',
    'mongolia': 'MNT',
    'kazakhstan': 'KZT',
    'uzbekistan': 'UZS',
    'tajikistan': 'TJS',
    'turkmenistan': 'TMT',
    'kyrgyzstan': 'KGS',
    'afghanistan': 'AFN',
    'iraq': 'IQD',
    'iran': 'IRR',
    'saudi arabia': 'SAR',
    'united arab emirates': 'AED',
    'qatar': 'QAR',
    'kuwait': 'KWD',
    'bahrain': 'BHD',
    'oman': 'OMR',
    'yemen': 'YER',
    'jordan': 'JOD',
    'lebanon': 'LBP',
    'syria': 'SYP',
    'israel': 'ILS',
    'palestine': 'ILS',
    'turkey': 'TRY',
    'armenia': 'AMD',
    'azerbaijan': 'AZN',
    'georgia': 'GEL',
    'cyprus': 'EUR',
    'maldives': 'MVR',
    'bhutan': 'BTN',
    'east timor': 'USD',
    'brunei': 'BND',
    'macau': 'MOP',
    // African countries
    'algeria': 'DZD',
    'angola': 'AOA',
    'benin': 'XOF',
    'botswana': 'BWP',
    'burkina faso': 'XOF',
    'burundi': 'BIF',
    'cabo verde': 'CVE',
    'cameroon': 'XAF',
    'central african republic': 'XAF',
    'chad': 'XAF',
    'comoros': 'KMF',
    'congo': 'XAF',
    'democratic republic of the congo': 'CDF',
    'djibouti': 'DJF',
    'egypt': 'EGP',
    'equatorial guinea': 'XAF',
    'eritrea': 'ERN',
    'eswatini': 'SZL',
    'ethiopia': 'ETB',
    'gabon': 'XAF',
    'gambia': 'GMD',
    'ghana': 'GHS',
    'guinea': 'GNF',
    'guinea-bissau': 'XOF',
    'ivory coast': 'XOF',
    'kenya': 'KES',
    'lesotho': 'LSL',
    'liberia': 'LRD',
    'libya': 'LYD',
    'madagascar': 'MGA',
    'malawi': 'MWK',
    'mali': 'XOF',
    'mauritania': 'MRU',
    'mauritius': 'MUR',
    'morocco': 'MAD',
    'mozambique': 'MZN',
    'namibia': 'NAD',
    'niger': 'XOF',
    'nigeria': 'NGN',
    'rwanda': 'RWF',
    'sao tome and principe': 'STN',
    'senegal': 'XOF',
    'seychelles': 'SCR',
    'sierra leone': 'SLL',
    'somalia': 'SOS',
    'south africa': 'ZAR',
    'south sudan': 'SSP',
    'sudan': 'SDG',
    'tanzania': 'TZS',
    'togo': 'XOF',
    'tunisia': 'TND',
    'uganda': 'UGX',
    'zambia': 'ZMW',
    'zimbabwe': 'ZWL',
    // Add more countries as needed
  };

  // Convert the input to lowercase for case-insensitive matching
  const normalizedCountry = countryName.toLowerCase().trim();
  
  // Return the currency code or USD as default if country not found
  return countryToCurrency[normalizedCountry] || 'USD';
}
